Dogs list feature
LiliaMamutova/dog_friends pull request #6
Opened 2023-10-14 14:15 UTC by LiliaMamutova

Added screen with List and Grid view, adaptation. Added images to assets

2023-10-14 16:09 UTC, AntonFesun commented on lib/dog_info.model.dart
> +  String featureOfDog;
please consider rename `featureOfDog `  to `dogFeatures`

2023-10-14 16:09 UTC, AntonFesun commented on lib/dog_info.model.dart
> +  DogInfo({
this class should be renamed to `DogModel`. As I can see you use this class just todisplay some data like name or birth date. So name of each item (class, method, property etc.) should have as more information about  as it can have in it's name and it should be clear, without the need, to look at implementation of class (or somth else).

2023-10-14 16:09 UTC, AntonFesun commented on lib/grid_dogs_widget.dart
> +class GridDogs extends StatelessWidget {
Suggest to rename it to something more clear: `DogsGridWidget`

2023-10-14 16:09 UTC, AntonFesun commented on lib/list_dogs_widget.dart
> +class ListDogs extends StatelessWidget {
Suggest to rename it to something more clear: DogsListWidget

2023-10-14 20:46 UTC, VadymPinchuk requested changes

2023-10-14 20:46 UTC, VadymPinchuk commented on assets/gifs/desktop_dogs_list_feature .gif
гіфки не треба додавати в Ассетс. оскільки ми їх не використовуємо у додатку. Вони мають бути в корені проекту

2023-10-14 20:46 UTC, VadymPinchuk commented on lib/dog_model.dart
прийшов час робити структуру проекту. **lib/data lib/presentation lib/domain** або як зручно тобі. в цілому можна в **lib** тримати головні файли типу main.dart та інші які використовуються у всіх екранах. А далі розбивати на **feature** типу **feature/login feature/list feature/ets**

2023-10-14 20:46 UTC, VadymPinchuk commented on lib/dogs_list_feature.dart
> +        MediaQuery.of(context).orientation == Orientation.landscape;
MediaQuery.orientationOf(context)

2023-10-14 20:46 UTC, VadymPinchuk commented on lib/dogs_list_feature.dart
> +    final bool isEnoughWidth = MediaQuery.of(context).size.width > 932;
sizeOf(context). але цифра 932 дуже магічна. треба пояснення чому вона така

2023-10-14 20:46 UTC, VadymPinchuk commented on lib/dogs_list_feature.dart
> +    final int columnsCount = isLandScape && isEnoughWidth ? 4 : 2;
isLandscape - не потрібно Scape виділяти

2023-10-14 20:46 UTC, VadymPinchuk commented on lib/grid_dogs_widget.dart
> +    return GridView.builder(
ЗАвдання було ніби про SliverGrid, але якщо для твого проекту це не потрібно - я ок з цим

2023-10-14 20:46 UTC, VadymPinchuk commented on lib/grid_dogs_widget.dart
> +        return Card(
Widget для кожного Item доволі складний і його можна було б винести в окремий метод.

2023-10-14 20:46 UTC, VadymPinchuk commented on lib/list_dogs_widget.dart
> +        return GestureDetector(
цей також

2023-10-14 20:46 UTC, VadymPinchuk commented on lib/theme_of_colors.dart
> +//
так не треба ) видали краще

2023-10-14 20:46 UTC, VadymPinchuk commented on pubspec.yaml
> -    # An image asset can refer to one or more resolution-specific "variants", see
форматер в дії )

2023-10-14 22:00 UTC, LiliaMamutova commented on assets/gifs/desktop_dogs_list_feature .gif
done

2023-10-14 22:00 UTC, LiliaMamutova commented on lib/dog_model.dart
done

2023-10-14 22:00 UTC, LiliaMamutova commented on lib/dogs_list_feature.dart
> +        MediaQuery.of(context).orientation == Orientation.landscape;
done

2023-10-14 22:21 UTC, LiliaMamutova commented on lib/dogs_list_feature.dart
> +    final bool isEnoughWidth = MediaQuery.of(context).size.width > 932;
done

2023-10-14 22:26 UTC, LiliaMamutova commented on lib/theme_of_colors.dart
> +//
done

2023-10-15 13:26 UTC, VadymPinchuk requested changes

2023-10-15 13:26 UTC, VadymPinchuk commented on lib/features/dog/widgets/list_dog_card_widget.dart
dog_card_list_widget.dart - такі імена мають більше сенсу

2023-10-15 13:26 UTC, VadymPinchuk commented on lib/features/dog/screen/dogs_list_feature.dart
dogs_list_screen.dart

2023-10-15 13:26 UTC, VadymPinchuk commented on lib/features/dog/widgets/grid_dog_card_widget.dart
dog_card_grid_widget

2023-10-15 16:24 UTC, merged